name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nginx-proxy:latest

      - name: Stop old containers
        run: sudo docker-compose down || true

      - name: Clean Docker
        run: sudo docker system prune -af || true

      - name: Run Nginx container
        run: sudo docker-compose up -d
