name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

        # 1️⃣ Ensure Docker network exists
      - name: Ensure Docker Network Exists
        run: |
          NETWORK_NAME=app-network
          if ! sudo docker network ls --format '{{.Name}}' | grep -wq "$NETWORK_NAME"; then
            echo "Creating Docker network: $NETWORK_NAME"
            sudo docker network create $NETWORK_NAME
          else
            echo "Docker network $NETWORK_NAME already exists"
          fi

      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nginx-proxy:latest

      - name: Stop old containers
        run: sudo docker compose down || true

      - name: Clean Docker
        run: sudo docker system prune -af || true

      - name: Run Nginx container
        run: sudo docker compose up -d
