name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  validate-nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Nginx config
        run: |
          docker run --rm -v $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro nginx:stable-alpine nginx -t

  build:
    runs-on: ubuntu-latest
    needs: [validate-nginx]
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-proxy:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-proxy:latest
